version: "3.9"

services:
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        - UID=${UID}
        - GID=${GID}
    volumes:
      - ./htdocs/:/var/www/html
    depends_on:
      - mysql
    user: "${UID}:${GID}"

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 8080:80
    depends_on:
      - php
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./htdocs/:/var/www/html

  db:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    build:
      context: .
      dockerfile: ./docker/phpmyadmin/Dockerfile
    environment:
      PMA_HOST: db
    ports:
      - 9080:80
    depends_on:
      - db

  mailhog:
    image: mailhog/mailhog
    ports:
      - '8025:8025'
      - '1025:1025'

volumes:
  db_data:

