version: "3.9"

volumes:
  mysql-volume:

services:
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./htdocs/:/var/www/html
    depends_on:
      - mysql

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 8080:80
    depends_on:
      - php
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./htdocs/:/var/www/html

  mysql:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - mysql-volume:/var/lib/mysql

  phpmyadmin:
    build:
      context: .
      dockerfile: ./docker/phpmyadmin/Dockerfile
    environment:
      PMA_HOST: mysql
    ports:
      - 9080:80
    depends_on:
      - mysql
